clone_depth: 1
version: '{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Debug
before_build:
  - cmd: nuget restore
build:
  project: NHentaiAPI.sln
  parallel: true
  verbosity: minimal